# -*- coding: utf-8 -*-
"""predictive-insight-engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T62pERDrfJVOAM8KSTUN0mZ-1p4_OcM5

# **Import Required Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor

"""# **Load Dataset**"""

file_path = 'RealEstate_HousePrice_Dataset.csv'

df = pd.read_csv(file_path)

print(df.head())

"""# **Dataset Information**"""

print(df.info())

print(df.isnull().sum())

print(df.describe())

"""# **Display Column Names**"""

print(df.columns)

"""# **Define Independent and Dependent Variables**"""

X = df.drop('house_price_inr', axis=1)

y = df['house_price_inr']

"""# **Convert Categorical Data**"""

X = pd.get_dummies(X, drop_first=True)

"""# **Data Visualization**

**Correlation Heatmap**
"""

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='Blues')
plt.title('Correlation Heatmap')
plt.show()

"""**Scatter Plot**"""

plt.figure(figsize=(8,6))
plt.scatter(df['area_sqft'], df['house_price_inr'])
plt.xlabel('Area Sqft')
plt.ylabel('House Price')
plt.title('Area vs House Price')
plt.show()

"""# **Split Dataset**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""# **Simple Linear Regression**
**Use Single Feature**
"""

X_simple = df[['area_sqft']]
y_simple = df['house_price_inr']

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_simple, y_simple, test_size=0.2, random_state=42
)

"""**Train Simple Linear Regression Model**"""

simple_model = LinearRegression()
simple_model.fit(X_train_s, y_train_s)

"""**Predictions**"""

y_pred_simple = simple_model.predict(X_test_s)

"""# **Plot Regression Line**"""

plt.figure(figsize=(8,6))
plt.scatter(X_simple, y_simple)
plt.plot(X_simple, simple_model.predict(X_simple), color='red')
plt.xlabel('Area Sqft')
plt.ylabel('House Price')
plt.title('Simple Linear Regression')
plt.show()

"""# **Model Evaluation**"""

mse = mean_squared_error(y_test_s, y_pred_simple)
mae = mean_absolute_error(y_test_s, y_pred_simple)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, y_pred_simple)

print('MSE:', mse)
print('MAE:', mae)
print('RMSE:', rmse)
print('R2 Score:', r2)

"""# **Residual Plot**"""

residuals = y_test_s - y_pred_simple

plt.figure(figsize=(8,6))
plt.scatter(y_pred_simple, residuals)
plt.axhline(y=0, color='red')
plt.xlabel('Predicted Values')
plt.ylabel('Residuals')
plt.title('Residual Plot')
plt.show()

"""# **Multiple Linear Regression**
**Train Multiple Linear Regression Model**
"""

multi_model = LinearRegression()
multi_model.fit(X_train, y_train)

"""**Predictions**"""

y_pred_multi = multi_model.predict(X_test)

"""**Evaluate Multiple Regression**"""

mse_multi = mean_squared_error(y_test, y_pred_multi)
rmse_multi = np.sqrt(mse_multi)
r2_multi = r2_score(y_test, y_pred_multi)

print('MSE:', mse_multi)
print('RMSE:', rmse_multi)
print('R2 Score:', r2_multi)

"""# **Polynomial Regression**
**Polynomial Regression**
"""

poly_model = make_pipeline(
    PolynomialFeatures(degree=2),
    LinearRegression()
)

poly_model.fit(X_train_s, y_train_s)

"""**Polynomial Predictions**"""

y_pred_poly = poly_model.predict(X_test_s)

"""**Evaluate Polynomial Regression**"""

poly_r2 = r2_score(y_test_s, y_pred_poly)

print('Polynomial Regression R2 Score:', poly_r2)

"""# **Feature Scaling**"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# **Batch Gradient Descent**"""

batch_model = SGDRegressor(
    max_iter=1000,
    eta0=0.01,
    learning_rate='constant',
    random_state=42
)

batch_model.fit(X_scaled, y)

"""# **Stochastic Gradient Descent**"""

sgd_model = SGDRegressor(
    max_iter=1000,
    learning_rate='optimal',
    random_state=42
)

sgd_model.fit(X_scaled, y)

